### PR TITLE
Merge discvr-19.3 to develop, automatically created

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Review by labkey-jeckels — APPROVED** [review]

**Comment by bbimber** [comment]
@labkey-jeckels thanks josh, but are you concerned about that build failure?  it is possible something is different on develop in the gradle plugin or how dependency requirements are declared?  my theory is that perhaps primeseq used to inherit the htsjdk dependency from sequenceanalysis-api, and maybe that's no longer allowed?

**Comment by labkey-jeckels** [comment]
@bbimber I just did a cursory code review, I didn't dig into the TeamCity results. Did this repro for you locally and/or find a fix for this?

**Comment by bbimber** [comment]
@labkey-jeckels I emailed w/ trey on this.  i think it is from the primeseq module not explicitly declaring the htsjdk dependency and/or the gradle plugin tightening.  susan pushed this recently:

https://github.com/LabKey/BimberLabKeyModules/commit/520ec67465b0441ad7d4fd7d83801a7aeb58b03e

and team city does appear to be building OK

**Comment by labkey-jeckels** [comment]
OK, great!

**Pull request merged**
