### PR TITLE
Eliminate unnecessary force

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
JAXB is no longer pulled in as a dependency

### CODE REVIEW

**Comment by labkey-adam** [comment]
@bbimber my change should be consistent with previous, however, it looks like mcc doesn't use JAXB, so I'm tempted to delete the `force` plus the reference over in SequenceAnalysis. LMK what you think. (Any chance to get rid of references to the old version is helpful, IMO.)

**Review by bbimber — APPROVED** [review]

**Comment by bbimber** [comment]
I will check it out. I think the force is purely to keep those two modules in sync, but it's been a long time. i dont believe they have very specific requirements around this

**Comment by labkey-adam** [comment]
> I will check it out. I think the force is purely to keep those two modules in sync, but it's been a long time. i dont believe they have very specific requirements around this

Sure, but there's no sign of JAXB being used by MCC. Examining its lib directory shows no JAXB jars. Removing the force and running `showDiscrepancies` results in no issues.

**Comment by bbimber** [comment]
OK, if you have looked at this and it passes w/o the exclude, then I imagine it's fine. I am pretty sure I added this exclude a long time ago to resolve something like a gradle discrepancy issue. If that's gone without this, it's probably better to drop it.

**Pull request merged**
