### PR TITLE
Merge discvr-20.11 to develop

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Comment by bbimber** [comment]
@labkey-adam See comments on this PR re: test failures: https://github.com/LabKey/DiscvrLabKeyModules/pull/87

**Comment by bbimber** [comment]
@labkey-jeckels OK, so this has to be the source of that change:

https://teamcity.labkey.org/viewModification.html?modId=387306&personal=false&tab=vcsModificationFiles&buildTypeId=bt310

**Comment by labkey-adam** [comment]
Yep, agreed

**Comment by bbimber** [comment]
@labkey-adam so how do you feel about approving these PRs? seems like the ContainerDisplayColumn thing is a separate issue

**Comment by labkey-adam** [comment]
I'm okay with the test failure. I'll give the files a quick review. I'm also checking with @labkey-susanh about whether the new modules should have a build.gradle file or not. (We're starting to be more strict about this.)

**Comment by bbimber** [comment]
ok. strict as in module should or should not default to having build.gradle? i typically needed to make one to declare dependencies.

**Comment by labkey-adam** [comment]
Strict as in requiring it in more cases. But you don't need to worry about it here; Susan's response: "Since both of these repos have a top-level build.gradle file that applies plugins to the subprojects there are no changes needed.  I've decided to not strictly require a build.gradle file everywhere, but will just eliminate our server/modules/build.gradle to eliminate its flawed logic."

**Review by labkey-adam — APPROVED** [review]

**Comment by labkey-jeckels** [comment]
Follow PR on the LabModulesTest failure. https://github.com/LabKey/platform/pull/1843

**Pull request merged**
