### PR TITLE
Merge discvr-20.3 to develop

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Review by labkey-jeckels — APPROVED** [review]
Looks fine, but should this go into the 20.7 branch?

**Comment by bbimber** [comment]
> Looks fine, but should this go into the 20.7 branch?

20.7 is a major release, right?  can i redirect an existing PR, or do I need to close this one and reopen?

**Comment by labkey-jeckels** [comment]
Yes, it's a major release.

Since develop and release20.7-SNAPSHOT are still very similar to each other, it should be enough to edit the existing PR and change the target branch. TeamCity won't run it against the 20.7 branch since the FB doesn't have the 20.7 prefix, but the current results are solid enough validation to not bother creating a new branch

**Comment by bbimber** [comment]
@labkey-jeckels I opened a separate PR to release20.7

**Pull request closed without merging**
