### PR TITLE
Merge discvr-19.3 to develop

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Review by labkey-tchad — CHANGES_REQUESTED** [review]
Getting startup errors on TeamCity:
ERROR ModuleUpgrader           2020-02-14 13:46:08,816           Module Upgrade : Failure during module upgrade
java.lang.AssertionError
	at org.labkey.api.module.DefaultModule.versionUpdate(DefaultModule.java:329)
	at org.labkey.api.module.ModuleUpgrader.upgrade(ModuleUpgrader.java:83)
	at org.labkey.api.module.ModuleUpgrader.lambda$upgrade$0(ModuleUpgrader.java:95)
	at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by bbimber** [comment]
@labkey-tchad I think this was related to getVersion/getSchemaVersion.  i dont know how to kick off teamcity builds from here though.

**Comment by bbimber** [comment]
@labkey-adam I think the issue might be primeseq module, which inherited hasScripts()=true, but does not implement getVersion() or getSchemaVersion().

In any case, what do you think about updating the assert in DefaultModule line 329?  It is a little cumbersome for me to do this.  It would be more informative like this:

assert null != getSchemaVersion() : "getSchemaVersion() was null for module: " + getName() + " even though hasScripts() was true";

**Comment by labkey-adam** [comment]
Yes, I can do this. Actually, I should probably relax this to a warning for now... I didn't mean it to break existing modules. But I think it's fair to add this check once we require getSchemaVersion(), etc. (after 20.3).

**Comment by bbimber** [comment]
@labkey-adam The tests pass now (mostly), and I would assume trunk/develop was also broken irrespective of my commits here.

I realize I'm seeing a test failure, but I dont think this is our code.  The stack stopImpersonatingRole() in the test harness.  It seems like maybe something isnt handling special characters well perhaps?


21:18:00,596     >>handleFailure('testSteps')
  java.lang.AssertionError: Element is not present: id=headerUserDropdown
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.labkey.test.WebDriverWrapper.assertElementPresent_aroundBody32(WebDriverWrapper.java:2335)
	at org.labkey.test.WebDriverWrapper.assertElementPresent_aroundBody33$advice(WebDriverWrapper.java:40)
	at org.labkey.test.WebDriverWrapper.assertElementPresent(WebDriverWrapper.java:1)
	at org.labkey.test.WebDriverWrapper.assertSignedInNotImpersonating(WebDriverWrapper.java:1171)
	at org.labkey.test.components.html.SiteNavBar.stopImpersonating(SiteNavBar.java:142)
	at org.labkey.test.LabKeySiteWrapper.stopImpersonating(LabKeySiteWrapper.java:1282)
	at org.labkey.test.LabKeySiteWrapper.stopImpersonating(LabKeySiteWrapper.java:1273)
	at org.labkey.test.LabKeySiteWrapper.stopImpersonatingRole(LabKeySiteWrapper.java:1262)
	at org.labkey.test.tests.external.labModules.LabModulesTest.overviewUITest(LabModulesTest.java:646)
	at org.labkey.test.tests.external.labModules.LabModulesTest.testSteps(LabModulesTest.java:221)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

**Review by labkey-tchad — APPROVED** [review]
That failure isn't a test bug but it doesn't appear to be a problem with this merge.

**Comment by bbimber** [comment]
@labkey-tchad yeah, that's more what i meant.  could be a test problem or product bug, but seems unlikely it's caused by these changes.

**Comment by labkey-adam** [comment]
@bbimber FYI: I changed that assert to a warning in this commit: https://github.com/LabKey/platform/commit/019265c85676b90216b6e6d756fd5aca3e7e7f61

**Pull request merged**
