### PR TITLE
Add nonces to all script tags

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
Strict CSPs require nonces

### CODE REVIEW

**Review by bbimber — APPROVED** [review]
Thanks @labkey-adam.

When you do these large refactors, are there easy ways to capture that in a way to help ensure future code complies? For example, I am about to do a merge that has some new views that lack this (I will try to fix those). 

There are build-based warnings that could identify patterns in files that are low enough effort to make worthwhile? Code inspections in intellij? lint-type tools? Point being that if you're putting all this effort into cleaning up the codebase, it would be nice to do that in a way that's lasting.

**Comment by labkey-adam** [comment]
> Thanks @labkey-adam.
> 
> When you do these large refactors, are there easy ways to capture that in a way to help ensure future code complies? For example, I am about to do a merge that has some new views that lack this (I will try to fix those).
> 
> There are build-based warnings that could identify patterns in files that are low enough effort to make worthwhile? Code inspections in intellij? lint-type tools? Point being that if you're putting all this effort into cleaning up the codebase, it would be nice to do that in a way that's lasting.

Our near-term solution for this is every developer and every test suite runs with a strict Content Security Policy. I recommend enabling a CSP locally. We'll soon run all TeamCity tests with strict checking on (most run this way today). So, if any person or test visits the page, the violation should be tracked and flagged. I realize this isn't a compile-time check. I'm open to augmenting with, say, IntelliJ checks. Understand that the rules are different for script tags in JSPs vs. wiki HTML vs. view/assay HTML vs. web resource HTML. But red squiggles under nonce-less script tags wouldn't hurt. However, I doubt this will help much for your upcoming merge. I suggest just doing a simple regex search after you merge and before you commit. This pattern works fairly well for me: `<script\s((?!nonce)(?!src)(?!path).)*>`

**Comment by bbimber** [comment]
hey @labkey-adam, OK, the test-based scheme seems reasonable. 

I get the spirit of doing a regex search prior to commits, and i will do this during my merge to develop because we just had this refactor. However, it doesnt really seem practical to think people are manually doing a panel of regex searches prior to commits (which might not actually be what you suggested). 

If not part of the build, would it make sense to have a core integration test that does something like: iterate every view in every module, execute some number of checks, and reports non-compliant views? An advantage of just iterating every single view is that it's probably faster than a selenium test and would inspect all views whether the selenium test hits it or not. Just trying to brainstorm more durable ways to approach this type of thing.

**Comment by labkey-adam** [comment]
> hey @labkey-adam, OK, the test-based scheme seems reasonable.
> 
> I get the spirit of doing a regex search prior to commits, and i will do this during my merge to develop because we just had this refactor. However, it doesnt really seem practical to think people are manually doing a panel of regex searches prior to commits (which might not actually be what you suggested).
> 
> If not part of the build, would it make sense to have a core integration test that does something like: iterate every view in every module, execute some number of checks, and reports non-compliant views? An advantage of just iterating every single view is that it's probably faster than a selenium test and would inspect all views whether the selenium test hits it or not. Just trying to brainstorm more durable ways to approach this type of thing.

No, I'm not suggesting doing regex searches before every commit. This was just for your upcoming "merge that has some new views that lack (script nonces)." An action that invokes all module views could have some value. IMO, it would only be valuable if it loads each view into a CSP-enabled browser (ideally FireFox, since it's pickier than Chrome) and tracks violations. It wouldn't have to be selenium-driven, but we already have a bunch of infrastructure in place in the integration test framework. This would basically be a different type of crawler. It's useful only if the majority of views can be displayed without any URL parameters... I hope that's the case.

**Comment by bbimber** [comment]
If this is more like static code analysis, would it need to actually render the view? Granted, that does not address all possible problems, but it would have found everything you found by doing a regex search in the code base, and becomes a durable insurance that things stay compliant.

**Comment by labkey-adam** [comment]
> If this is more like static code analysis, would it need to actually render the view? Granted, that does not address all possible problems, but it would have found everything you found by doing a regex search in the code base, and becomes a durable insurance that things stay compliant.

I created a simple junit test that detects nonce-less script tags and inline handlers. It detected a few tags and event handlers that my regexes missed. https://github.com/LabKey/platform/pull/5314

**Pull request merged**
